trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds


steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: salahdinnnnn
    command: build
    Dockerfile: Dockerfile
    
- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'jfrog.repo'
    targetRepo: 'salahdin-jfrog-docker-local'
    collectBuildInfo: true
    imageName: 'salahdin:1.0'
