trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
    
variables:
  imageName: 'my-test-image'  
  dockerRegistryServiceConnection : 'Docker'
  imageRepository : 'docker-local'
  dockerfilePath : Dockerfile
  artifactoryServiceConnection : 'jfrog'
  targetRepo : 'docker-local'
  imageTag : '20220512.22'
    
    
steps:
  
  
- task: Docker@2
  displayName: "Docker Build"
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(imageRepository)'
    command: 'build'
    Dockerfile: '$(dockerfilePath)'
    tags: '20220512.22'

      
- task: ArtifactoryDocker@1
  displayName: "Docker push"
  inputs:
    command: 'push'
    artifactoryService: '$(artifactoryServiceConnection)'
    targetRepo: '$(targetRepo)'
    imageName: '$(imageName):$(imageTag)'

   
