trigger:
- main


pool: Default
 
    
variables:
  imageName: 'salahdin.jfrog.io/docker-local/my-iimage'  
  dockerRegistryServiceConnection : 'Docker'
  imageRepository : 'docker-local/my-iimage'
  dockerfilePath : Dockerfile
  artifactoryServiceConnection : 'jfrog'
  targetRepo : 'docker-local'
  imageTag : '$(Build.BuildNumber)'
    
    
steps:
  
  



- task: Docker@2
  displayName: "Docker Build"
  inputs:
    command: 'build'
    Dockerfile: '$(dockerfilePath)'
    tags: '$(Build.BuildNumber)'


