trigger:
- main

pool: Self-Hosted
 
    
variables:
  imageName: 'salahdin.jfrog.io/docker-local/my-iiimage'  
  dockerRegistryServiceConnection : 'Docker'
  imageRepository : 'docker-local/my-iiimage'
  dockerfilePath : Dockerfile
  artifactoryServiceConnection : 'jfrog'
  targetRepo : 'docker-local'
  imageTag : '$(Build.BuildNumber)'
    
    
steps:
  
  
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'salahdinhafez0883'
    scannerMode: 'MSBuild'
    projectKey: 'salahdinhafez0883_Jfrog-with-sonar-cloud'
    projectName: 'Jfrog with sonar cloud'



- task: Docker@2
  displayName: "Docker Build"
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(imageRepository)'
    command: 'build'
    Dockerfile: '$(dockerfilePath)'
    tags: '$(Build.BuildNumber)'


- task: SonarCloudAnalyze@1

      
      
- task: ArtifactoryDocker@1
  displayName: "Docker push"
  inputs:
    command: 'push'
    artifactoryService: '$(artifactoryServiceConnection)'
    targetRepo: '$(targetRepo)'
    imageName: '$(imageName):$(imageTag)'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
