trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
    
variables:
  imageName: 'salahdin.jfrog.io/hoda-docker'  
  dockerRegistryServiceConnection : 'Docker'
  imageRepository :
  dockerfilePath : Dockerfile
  artifactoryServiceConnection : 'jfrog'
  targetRepo : 'hoda-docker'
  imageTag : '$(Build.BuildNumber)'
    
    
steps:
  
  
- task: Docker@2
    displayName: "Docker Build"
    inputs:
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: '$(imageRepository)'
      command: 'build'
      Dockerfile: '$(dockerfilePath)'
      tags: '$(Build.BuildNumber)'

      
- task: ArtifactoryDocker1
    displayName: "Docker push"
    inputs:
      command: 'push'
      artifactoryService: '$(artifactoryServiceConnection)'
      targetRepo: '$(targetRepo)'
      imageName: '$(imageName):$(imageTag)'

   
