trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
container : jfrogecosystem/jfrog-setup-cli
    
variables:
  imageName: 'salahdin.jfrog.io/salahdindocker'  
  dockerRegistryServiceConnection : 'Docker'
  imageRepository : 'salahdindocker'
  dockerfilePath : Dockerfile
  artifactoryServiceConnection : 'jfrog'
  targetRepo : 'salahdindocker'
  imageTag : '$(Build.BuildNumber)'
    
    
steps:
  
  
- task: Docker@2
  displayName: "Docker Build"
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(imageRepository)'
    command: 'build'
    Dockerfile: '$(dockerfilePath)'
    tags: '$(Build.BuildNumber)'

      
- task: ArtifactoryDocker@1
  displayName: "Docker push"
  inputs:
    command: 'push'
    artifactoryService: '$(artifactoryServiceConnection)'
    targetRepo: '$(targetRepo)'
    imageName: '$(imageName):$(imageTag)'

   
