trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds


steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    command: build
    Dockerfile: Dockerfile

- task: ArtifactoryDocker@1
  displayName: push an image
  inputs:
    command: 'push'
    artifactoryService: 'jfrog'
    targetRepo: 'salahdin-jfrog-docker-local'
    collectBuildInfo: true
    imageName: 'salahdin.jfrog.io/salahdin-jfrog-docker-local:latest'

    
    
    
    
    
    
    
    
