trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds


steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: 'salahdin.jfrog.io/salahdin-jfrog-docker/sa'
    command: build
    Dockerfile: Dockerfile
    tags : 'latest'
    
- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'jfrog'
    targetRepo: 'salahdin-jfrog-docker'
    imageName: 'salahdin.jfrog.io/salahdin-jfrog-docker/sa:latest'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    
    
    
    
    
    
    
    
