trigger:
- main

pool:
  name: Self-Hosted

variables:
  imageName: 'salahdin.jfrog.io/docker-local/my-image'  
  dockerRegistryServiceConnection : 'Docker'
  imageRepository : 'docker-local/my-image'
  dockerfilePath : Dockerfile
  artifactoryServiceConnection : 'jfrog'
  targetRepo : 'docker-local'
  imageTag : '$(Build.BuildNumber)'
    
    
steps:

- task: Docker@2
  displayName: "Docker Build"
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(imageRepository)'
    command: 'build'
    Dockerfile: '$(dockerfilePath)'
    tags: '$(Build.BuildNumber)'



      
      
- task: ArtifactoryDocker@1
  displayName: "Docker push"
  inputs:
    command: 'push'
    artifactoryService: '$(artifactoryServiceConnection)'
    targetRepo: '$(targetRepo)'
    imageName: '$(imageName):$(imageTag)'

