trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds


steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    command: build
    Dockerfile: Dockerfile

- task: Docker@2
  displayName: Push Docker image
  inputs:
    containerRegistry: 'jfrog'
    repository: 'salahdin-jfrog-docker-local'
    command: 'push'
    tags: 'latest'
    
    
    
    
    
    
    
    
