trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds

variables:
  imageeName: 'pipelines-nigix-docker'
  artifactoryServiceConnection: 'jfrog.repo'
  targetRepo: 'salahdin-jfrog-docker-local'
  imageTag: '$(Build.BuildName)'
  
  
steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageeName)
    command: build
    Dockerfile: Dockerfile
    
- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: '$(artifactoryServiceConnection)'
    targetRepo: '$(targetRepo)'
    imageName: '$(imageeName):$(imageTag)'

