trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds


steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'Docker'
    repository: 'salahdin-jfrog-docker-local'
    command: build
    Dockerfile: Dockerfile
    tags : 'latest'
    
- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'jfrog.repo'
    targetRepo: 'salahdin-jfrog-docker-local'
    collectBuildInfo: true
    imageName: 'salahdin.jfrog.io/salahdin-jfrog-docker-local:latest'
